name: ChaosBoard
main: org.chaospvp.board.ChaosBoard
version: ${project.version}
author: vemacs
depend: [Factions, WorldGuard, Vault]
commands:
  cbtoggle:
    permission: chaosboard.toggle
    usage: /cbtoggle
permissions:
  chaosboard.toggle:
    default: false
