name: ChaosBoard
main: org.chaospvp.board.ChaosBoard
version: ${project.version}
author: vemacs
depend: [Factions, WorldGuard, Vault]
commands:
  sbtoggle:
    description: Toggles ChaosBoard
    usage: /sbtoggle